CREATE TABLE IF NOT EXISTS public.farmer
(
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  name character varying,
  surname character varying,
  CONSTRAINT farmer_pkey PRIMARY KEY (id)
);
CREATE TABLE IF NOT EXISTS public.type
(
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  name character varying,
  CONSTRAINT type_pkey PRIMARY KEY (id)
);
CREATE TABLE IF NOT EXISTS  public.animal
(
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  name character varying,
  weight double precision,
  farmer_id bigint,
  type_id bigint,
  CONSTRAINT animal_pkey PRIMARY KEY (id),
  CONSTRAINT "FK_FARMER" FOREIGN KEY (farmer_id) REFERENCES public.farmer (id) MATCH SIMPLE,
  CONSTRAINT "FK_TYPE" FOREIGN KEY (type_id) REFERENCES public.type (id) MATCH SIMPLE
);

